"""Alternate app launcher (clean) — use this to run the Gradio UI.

This avoids the large autogenerated `app.py` content and provides a simple
entrypoint: `python run_app.py`.
"""
from rag_study_buddy.rag_pipeline import RAGPipeline
from rag_study_buddy.ui.ui_app import build_ui


def main():
    pipeline = RAGPipeline(persist_dir="./data/index", gen_model="distilgpt2")
    app = build_ui(pipeline, title="RAG Study Buddy (run_app)")
    app.launch()


if __name__ == "__main__":
    main()
